# Generated by Django 5.2 on 2025-04-11 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название стола')),
                ('seats', models.IntegerField(verbose_name='Количество мест')),
                ('location', models.CharField(choices=[('window hall', 'Зал у окна'), ('main hall', 'Основной зал'), ('terrace', 'Терраса')], default='main hall', max_length=50, verbose_name='Расположение стола')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Имя посетителя')),
                ('reservation_time', models.DateTimeField(verbose_name='Время брони')),
                ('duration_minutes', models.IntegerField(verbose_name='Длительность брони')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.table', verbose_name='Номер стола')),
            ],
        ),
    ]
